logoText = "ÊàëÁöÑÂ≠¶‰π†ÂçöÂÆ¢"
logoType = "short" # long, short
description = "Â•ΩÂ•ΩÂ≠¶‰π†ÔºåÂ§©Â§©Âêë‰∏ä„ÄÇ"
custom_css = []
custom_js = []
useFaviconGenerator = true # https://www.favicon-generator.org/
meta_image = ""
themecolor = ""

themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
notAllowedTypesInHome = ["notshow","contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["notshow","about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["notshow","about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["notshow","about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = true
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = true
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# appbar
enableAppbarSearchIcon = true
enableAppbarLangIcon = false

# header
homeHeaderType = "text" # text, img, slide, typewriter
hideHomeHeaderWhenMobile = false

# menu
showMobileMenuTerms = ["tags", "categories", "series"]

# search
enableSearch = true
enableSearchHighlight = true
searchResultPosition = "main" # side, main
searchContent = true # include content to search index
searchDistance = 100 # fuse option
searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

# body
enableBreadcrumb = true
enableGoToTop = true
enableWhoami = false
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20
writtenTimeIcon = "üìÖ"
modifiedTimeIcon = "üìù"
readingTimeIcon = "‚òï"
authorIcon = "‚úçÔ∏è"
pagePvIcon = "üëÄ"
pinIcon = "üìå"
tagIcon = "üè∑Ô∏è"
publicationIcon = "üìö"
typeIcon = "üéØ"

# whoami
#myname = "YSL"
#email = "yslinwe@gmail.com"
#whoami = "Web Developer"
#bioImageUrl = ""
#useGravatar = ""
#location = "GuangZhou, China"
#organization = "Hello"
#link = "https://yslinwe.github.io"

# sidebar
enableBio = true
enableBioImage = false
enableSidebar = true
enableSidebarTags = true
enableSidebarSeries = true
enableSidebarCategories = true
enableHomeSidebarTitles = true
enableListSidebarTitles = true
enableToc = true
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = true
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = true

# footer
showPoweredBy = true
showFeedLinks = false
showSocialLinks = false
enableLangChange = false
enableThemeChange = true

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = true
busuanziSitePV = true
busuanziPagePV = true

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = true
disqus_shortname = ""
commento = false

[telegram]
  enable = false
  siteId = ""
  dataLimit = 5

[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments
  clientId = ""           # Your client ID
  clientSecret = ""       # Your client secret

[utterances]       # https://utteranc.es/
  owner = ""              # Your GitHub ID
  repo = ""               # The repo to store comments

[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  owner = "popoYSL"              # Your GitHub ID
  repo = "https://github.com/popoYSL/git-commits"               # The repo to store comments
  clientId = "e1d61566fcef3be23349"           # Your client ID
  clientSecret = "8040097e71904cfc2a44e740939e74faf13f0882"       # Your client secret

# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[valine]
  enable = false
  appId = '‰Ω†ÁöÑappId'
  appKey = '‰Ω†ÁöÑappKey'
  notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
  verify = false # Verification code
  avatar = 'mm' 
  placeholder = 'ËØ¥ÁÇπ‰ªÄ‰πàÂêß...'
  visitor = false

[changyan]
  changyanAppid = ""        # Changyan app id             # ÁïÖË®Ä
  changyanAppkey = ""       # Changyan app key

[livere]
  livereUID = ""            # LiveRe UID                  # Êù•ÂøÖÂäõ

# Isso: https://posativ.org/isso/
[isso]
  enable = false
  scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
  dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[socialOptions]
  email = "mailto:your@email.com"
  phone = ""
  facebook = ""
  twitter = ""
  github = "https://github.com/yslinwe"
  gitlab = "https://gitee.com/yslinxx"
  stack-overflow = ""
  instagram = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  whatsapp = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""